### ISSUE TITLE
Installation guidance

### ISSUE THREAD

**Issue by hugoroy** [alpernebbi/git-annex-metadata-gui#9]
Hello,

I have installed git-annex-adapter and pyqt5 but I can't install this.

Some installation guidance or pointers in the readme would be appreciated.

Thanks!

**Comment by alpernebbi** [comment]
I've recently rewritten git-annex-adapter and pushed it as `v0.2.0`. I'm also rewriting this project, but it's not so complete, so I haven't uploaded my progress yet. The current code is for `v0.1.0`, you can downgrade and try installing again or you can wait a few days for me to upload a new version.

**Comment by hugoroy** [comment]
↪ Alper Nebi Yasak / août 12, 2017 21:53:
> I've recently rewritten git-annex-adapter and pushed it as `v0.2.0`. I'm also rewriting this project, but it's not so complete, so I haven't uploaded my progress yet. The current code is for `v0.1.0`, you can downgrade and try installing again or you can wait a few days for me to upload a new version.

That's okay, I can wait :)

Let me know if you want some testing and first-use experience feedback.

**Comment by alpernebbi** [comment]
Hi. I've just uploaded the new version, both here and to [PyPI](https://pypi.org/project/git-annex-metadata-gui/). I think running `pip3 install git-annex-metadata-gui` should do the job. Can you try and let me know?

**Comment by hugoroy** [comment]
Hi, I got this:

    Requirement already satisfied: git-annex-metadata-gui in /usr/lib/python3.6/site-packages/git_annex_metadata_gui-0.1.0-py3.6.egg
    Collecting PyQt5 (from git-annex-metadata-gui)
    Downloading PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (104.6MB)
        100% |████████████████████████████████| 104.6MB 14kB/s 
    Collecting git-annex-adapter==0.1.0 (from git-annex-metadata-gui)
    Could not find a version that satisfies the requirement git-annex-adapter==0.1.0 (from git-annex-metadata-gui) (from versions: 0.2.0)
    No matching distribution found for git-annex-adapter==0.1.0 (from git-annex-metadata-gui)

**Comment by alpernebbi** [comment]
It's still trying to work with the old installed version, try uninstalling then reinstalling, or maybe `pip3 install git-annex-metadata-gui==0.2.0`.

**Comment by hugoroy** [comment]
↪ Alper Nebi Yasak / août 24, 2017 0:04:
> It's still trying to work with the old installed version, try uninstalling then reinstalling, or maybe `pip3 install git-annex-metadata-gui==0.2.0`.

This worked! Thanks :-)
